CC = gcc
WINDRES = windres
CFLAGS = -Wall -Wextra -std=c99 -I./header -I.

LDFLAGS = -lraylib -lopengl32 -lgdi32 -lwinmm -lm

TARGET = Elevator_Simulation.exe
RES_FILE = resource.rc
RES_OBJ = resource.o

SRCS = Main.c src/About.c src/BuildingView.c src/Camera.c src/Guide.c src/Lift.c src/MechView.c src/Menu.c src/Simulation.c src/Transformasi.c src/UI.c src/Person.c

.PHONY: all clean rebuild

all: $(TARGET)

$(RES_OBJ): $(RES_FILE)
	$(WINDRES) $(RES_FILE) -o $(RES_OBJ)

$(TARGET): $(RES_OBJ)
	$(CC) $(CFLAGS) $(SRCS) $(RES_OBJ) -o $(TARGET) $(LDFLAGS)

clean:
	-cmd /c del $(TARGET) $(RES_OBJ)

rebuild: clean all

# Cara pakai di Windows:
# 1. Buka terminal 
# 2. Build biasa: mingw32-make -f Makefile.win
# 3. Paksa Timpa: mingw32-make -f Makefile.win rebuild